version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-docker:
    docker:
      - image: circleci/python:3.7  # Adjust the base image as required
    environment:
      - UDAGRAM_API_FEED_IMAGE_NAME: udagram-api-feed
      - UDAGRAM_API_USER_IMAGE_NAME: udagram-api-user
      - UDAGRAM_FRONTEND_IMAGE_NAME: udagram-frontend
      - UDAGRAM_REVERSEPROXY_IMAGE_NAME: reverseproxy
      - TAG: latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f ./docker-compose-build.yaml build --parallel
            docker tag $UDAGRAM_API_FEED_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_API_USER_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_FRONTEND_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_REVERSEPROXY_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG
  push-docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-docker
      - push-docker:
          requires:
            - build-docker
