version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f ./docker-compose-build.yaml build --parallel
      - run:
          name: Verify Built Images
          command: |
            docker images  # Check if all images were built
  push-docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Images
          command: |
            docker-compose -f ./docker-compose-build.yaml push --parallel

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-docker
      - push-docker:
          requires:
            - build-docker
