version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-docker:
    docker:
      - image: circleci/python:3.7  # Adjust the base image as required
    environment:
      - UDAGRAM_API_FEED_IMAGE_NAME: udagram-api-feed
      - UDAGRAM_API_USER_IMAGE_NAME: udagram-api-user
      - UDAGRAM_FRONTEND_IMAGE_NAME: udagram-frontend
      - UDAGRAM_REVERSEPROXY_IMAGE_NAME: reverseproxy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Auto-increment TAG
          command: |
            # Fetch the latest tags from the repository
            git fetch --tags

            # Get the latest tag, default to v1 if no tag is found
            TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1")

            # Increment the numeric part of the tag (e.g., v1 -> v2)
            NEW_TAG=$(echo $TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

            # Print out the new tag for visibility in the logs
            echo "New TAG version: $NEW_TAG"

            # Use the new tag in further steps
            echo "export TAG=$NEW_TAG" >> $BASH_ENV
      - run:
          name: Build Docker Images
          command: |
            docker-compose -f ./docker-compose-build.yaml build --parallel
            docker tag $UDAGRAM_API_FEED_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_API_USER_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_FRONTEND_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
            docker tag $UDAGRAM_REVERSEPROXY_IMAGE_NAME $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG
  push-docker:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker Images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/$UDAGRAM_API_FEED_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_API_USER_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_FRONTEND_IMAGE_NAME:$TAG
            docker push $DOCKER_USERNAME/$UDAGRAM_REVERSEPROXY_IMAGE_NAME:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-docker
      - push-docker:
          requires:
            - build-docker
